package com.lgs.entity;

public interface CaoZuoBiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caozuobiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caozuobiao
     *
     * @mbg.generated
     */
    int insert(CaoZuoBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caozuobiao
     *
     * @mbg.generated
     */
    int insertSelective(CaoZuoBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caozuobiao
     *
     * @mbg.generated
     */
    CaoZuoBiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caozuobiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CaoZuoBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table caozuobiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CaoZuoBiao record);
}