package com.lgs.entity;

import java.util.Date;

public class CaoZuoBiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caozuobiao.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caozuobiao.yonghu_id
     *
     * @mbg.generated
     */
    private String yonghuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caozuobiao.shijian
     *
     * @mbg.generated
     */
    private String shijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caozuobiao.time
     *
     * @mbg.generated
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caozuobiao.temp1
     *
     * @mbg.generated
     */
    private String temp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caozuobiao.temp2
     *
     * @mbg.generated
     */
    private String temp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caozuobiao.temp3
     *
     * @mbg.generated
     */
    private String temp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caozuobiao.temp4
     *
     * @mbg.generated
     */
    private String temp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column caozuobiao.temp5
     *
     * @mbg.generated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caozuobiao.id
     *
     * @return the value of caozuobiao.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caozuobiao.id
     *
     * @param id the value for caozuobiao.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caozuobiao.yonghu_id
     *
     * @return the value of caozuobiao.yonghu_id
     *
     * @mbg.generated
     */
    public String getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caozuobiao.yonghu_id
     *
     * @param yonghuId the value for caozuobiao.yonghu_id
     *
     * @mbg.generated
     */
    public void setYonghuId(String yonghuId) {
        this.yonghuId = yonghuId == null ? null : yonghuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caozuobiao.shijian
     *
     * @return the value of caozuobiao.shijian
     *
     * @mbg.generated
     */
    public String getShijian() {
        return shijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caozuobiao.shijian
     *
     * @param shijian the value for caozuobiao.shijian
     *
     * @mbg.generated
     */
    public void setShijian(String shijian) {
        this.shijian = shijian == null ? null : shijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caozuobiao.time
     *
     * @return the value of caozuobiao.time
     *
     * @mbg.generated
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caozuobiao.time
     *
     * @param time the value for caozuobiao.time
     *
     * @mbg.generated
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caozuobiao.temp1
     *
     * @return the value of caozuobiao.temp1
     *
     * @mbg.generated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caozuobiao.temp1
     *
     * @param temp1 the value for caozuobiao.temp1
     *
     * @mbg.generated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caozuobiao.temp2
     *
     * @return the value of caozuobiao.temp2
     *
     * @mbg.generated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caozuobiao.temp2
     *
     * @param temp2 the value for caozuobiao.temp2
     *
     * @mbg.generated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caozuobiao.temp3
     *
     * @return the value of caozuobiao.temp3
     *
     * @mbg.generated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caozuobiao.temp3
     *
     * @param temp3 the value for caozuobiao.temp3
     *
     * @mbg.generated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caozuobiao.temp4
     *
     * @return the value of caozuobiao.temp4
     *
     * @mbg.generated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caozuobiao.temp4
     *
     * @param temp4 the value for caozuobiao.temp4
     *
     * @mbg.generated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column caozuobiao.temp5
     *
     * @return the value of caozuobiao.temp5
     *
     * @mbg.generated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column caozuobiao.temp5
     *
     * @param temp5 the value for caozuobiao.temp5
     *
     * @mbg.generated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
}