package com.lgs.entity;

public class FenLeiBiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenleibiao.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenleibiao.fenleiming
     *
     * @mbg.generated
     */
    private String fenleiming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenleibiao.temp1
     *
     * @mbg.generated
     */
    private String temp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenleibiao.temp2
     *
     * @mbg.generated
     */
    private String temp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenleibiao.temp3
     *
     * @mbg.generated
     */
    private String temp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenleibiao.temp4
     *
     * @mbg.generated
     */
    private String temp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fenleibiao.temp5
     *
     * @mbg.generated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenleibiao.id
     *
     * @return the value of fenleibiao.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenleibiao.id
     *
     * @param id the value for fenleibiao.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenleibiao.fenleiming
     *
     * @return the value of fenleibiao.fenleiming
     *
     * @mbg.generated
     */
    public String getFenleiming() {
        return fenleiming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenleibiao.fenleiming
     *
     * @param fenleiming the value for fenleibiao.fenleiming
     *
     * @mbg.generated
     */
    public void setFenleiming(String fenleiming) {
        this.fenleiming = fenleiming == null ? null : fenleiming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenleibiao.temp1
     *
     * @return the value of fenleibiao.temp1
     *
     * @mbg.generated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenleibiao.temp1
     *
     * @param temp1 the value for fenleibiao.temp1
     *
     * @mbg.generated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenleibiao.temp2
     *
     * @return the value of fenleibiao.temp2
     *
     * @mbg.generated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenleibiao.temp2
     *
     * @param temp2 the value for fenleibiao.temp2
     *
     * @mbg.generated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenleibiao.temp3
     *
     * @return the value of fenleibiao.temp3
     *
     * @mbg.generated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenleibiao.temp3
     *
     * @param temp3 the value for fenleibiao.temp3
     *
     * @mbg.generated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenleibiao.temp4
     *
     * @return the value of fenleibiao.temp4
     *
     * @mbg.generated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenleibiao.temp4
     *
     * @param temp4 the value for fenleibiao.temp4
     *
     * @mbg.generated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fenleibiao.temp5
     *
     * @return the value of fenleibiao.temp5
     *
     * @mbg.generated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fenleibiao.temp5
     *
     * @param temp5 the value for fenleibiao.temp5
     *
     * @mbg.generated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
}