package com.lgs.entity;

public interface GongYingShangBiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshangbiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshangbiao
     *
     * @mbg.generated
     */
    int insert(GongYingShangBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshangbiao
     *
     * @mbg.generated
     */
    int insertSelective(GongYingShangBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshangbiao
     *
     * @mbg.generated
     */
    GongYingShangBiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshangbiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GongYingShangBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gongyingshangbiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GongYingShangBiao record);
}