package com.lgs.entity;

public class KuCunBiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.shangpin_id
     *
     * @mbg.generated
     */
    private String shangpinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.shuliang
     *
     * @mbg.generated
     */
    private String shuliang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.cangku_id
     *
     * @mbg.generated
     */
    private String cangkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.rukushijian
     *
     * @mbg.generated
     */
    private String rukushijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.rukuyonghu
     *
     * @mbg.generated
     */
    private String rukuyonghu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.baozhiqikaishi
     *
     * @mbg.generated
     */
    private String baozhiqikaishi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.baozhiqijieshu
     *
     * @mbg.generated
     */
    private String baozhiqijieshu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.bianhao
     *
     * @mbg.generated
     */
    private String bianhao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.shenheyonghu
     *
     * @mbg.generated
     */
    private String shenheyonghu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.temp1
     *
     * @mbg.generated
     */
    private String temp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.temp2
     *
     * @mbg.generated
     */
    private String temp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.temp3
     *
     * @mbg.generated
     */
    private String temp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.temp4
     *
     * @mbg.generated
     */
    private String temp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kucunbiao.temp5
     *
     * @mbg.generated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.id
     *
     * @return the value of kucunbiao.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.id
     *
     * @param id the value for kucunbiao.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.shangpin_id
     *
     * @return the value of kucunbiao.shangpin_id
     *
     * @mbg.generated
     */
    public String getShangpinId() {
        return shangpinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.shangpin_id
     *
     * @param shangpinId the value for kucunbiao.shangpin_id
     *
     * @mbg.generated
     */
    public void setShangpinId(String shangpinId) {
        this.shangpinId = shangpinId == null ? null : shangpinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.shuliang
     *
     * @return the value of kucunbiao.shuliang
     *
     * @mbg.generated
     */
    public String getShuliang() {
        return shuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.shuliang
     *
     * @param shuliang the value for kucunbiao.shuliang
     *
     * @mbg.generated
     */
    public void setShuliang(String shuliang) {
        this.shuliang = shuliang == null ? null : shuliang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.cangku_id
     *
     * @return the value of kucunbiao.cangku_id
     *
     * @mbg.generated
     */
    public String getCangkuId() {
        return cangkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.cangku_id
     *
     * @param cangkuId the value for kucunbiao.cangku_id
     *
     * @mbg.generated
     */
    public void setCangkuId(String cangkuId) {
        this.cangkuId = cangkuId == null ? null : cangkuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.rukushijian
     *
     * @return the value of kucunbiao.rukushijian
     *
     * @mbg.generated
     */
    public String getRukushijian() {
        return rukushijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.rukushijian
     *
     * @param rukushijian the value for kucunbiao.rukushijian
     *
     * @mbg.generated
     */
    public void setRukushijian(String rukushijian) {
        this.rukushijian = rukushijian == null ? null : rukushijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.rukuyonghu
     *
     * @return the value of kucunbiao.rukuyonghu
     *
     * @mbg.generated
     */
    public String getRukuyonghu() {
        return rukuyonghu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.rukuyonghu
     *
     * @param rukuyonghu the value for kucunbiao.rukuyonghu
     *
     * @mbg.generated
     */
    public void setRukuyonghu(String rukuyonghu) {
        this.rukuyonghu = rukuyonghu == null ? null : rukuyonghu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.baozhiqikaishi
     *
     * @return the value of kucunbiao.baozhiqikaishi
     *
     * @mbg.generated
     */
    public String getBaozhiqikaishi() {
        return baozhiqikaishi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.baozhiqikaishi
     *
     * @param baozhiqikaishi the value for kucunbiao.baozhiqikaishi
     *
     * @mbg.generated
     */
    public void setBaozhiqikaishi(String baozhiqikaishi) {
        this.baozhiqikaishi = baozhiqikaishi == null ? null : baozhiqikaishi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.baozhiqijieshu
     *
     * @return the value of kucunbiao.baozhiqijieshu
     *
     * @mbg.generated
     */
    public String getBaozhiqijieshu() {
        return baozhiqijieshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.baozhiqijieshu
     *
     * @param baozhiqijieshu the value for kucunbiao.baozhiqijieshu
     *
     * @mbg.generated
     */
    public void setBaozhiqijieshu(String baozhiqijieshu) {
        this.baozhiqijieshu = baozhiqijieshu == null ? null : baozhiqijieshu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.bianhao
     *
     * @return the value of kucunbiao.bianhao
     *
     * @mbg.generated
     */
    public String getBianhao() {
        return bianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.bianhao
     *
     * @param bianhao the value for kucunbiao.bianhao
     *
     * @mbg.generated
     */
    public void setBianhao(String bianhao) {
        this.bianhao = bianhao == null ? null : bianhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.shenheyonghu
     *
     * @return the value of kucunbiao.shenheyonghu
     *
     * @mbg.generated
     */
    public String getShenheyonghu() {
        return shenheyonghu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.shenheyonghu
     *
     * @param shenheyonghu the value for kucunbiao.shenheyonghu
     *
     * @mbg.generated
     */
    public void setShenheyonghu(String shenheyonghu) {
        this.shenheyonghu = shenheyonghu == null ? null : shenheyonghu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.temp1
     *
     * @return the value of kucunbiao.temp1
     *
     * @mbg.generated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.temp1
     *
     * @param temp1 the value for kucunbiao.temp1
     *
     * @mbg.generated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.temp2
     *
     * @return the value of kucunbiao.temp2
     *
     * @mbg.generated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.temp2
     *
     * @param temp2 the value for kucunbiao.temp2
     *
     * @mbg.generated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.temp3
     *
     * @return the value of kucunbiao.temp3
     *
     * @mbg.generated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.temp3
     *
     * @param temp3 the value for kucunbiao.temp3
     *
     * @mbg.generated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.temp4
     *
     * @return the value of kucunbiao.temp4
     *
     * @mbg.generated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.temp4
     *
     * @param temp4 the value for kucunbiao.temp4
     *
     * @mbg.generated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kucunbiao.temp5
     *
     * @return the value of kucunbiao.temp5
     *
     * @mbg.generated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kucunbiao.temp5
     *
     * @param temp5 the value for kucunbiao.temp5
     *
     * @mbg.generated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
}