package com.lgs.entity;

public interface KuCunBiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucunbiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucunbiao
     *
     * @mbg.generated
     */
    int insert(KuCunBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucunbiao
     *
     * @mbg.generated
     */
    int insertSelective(KuCunBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucunbiao
     *
     * @mbg.generated
     */
    KuCunBiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucunbiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KuCunBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kucunbiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KuCunBiao record);
}