package com.lgs.entity;

public class ShangPingBiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangpinbiao.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangpinbiao.feilei_id
     *
     * @mbg.generated
     */
    private String feileiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangpinbiao.shangpin
     *
     * @mbg.generated
     */
    private String shangpin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangpinbiao.temp1
     *
     * @mbg.generated
     */
    private String temp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangpinbiao.temp2
     *
     * @mbg.generated
     */
    private String temp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangpinbiao.temp3
     *
     * @mbg.generated
     */
    private String temp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangpinbiao.temp4
     *
     * @mbg.generated
     */
    private String temp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shangpinbiao.temp5
     *
     * @mbg.generated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangpinbiao.id
     *
     * @return the value of shangpinbiao.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangpinbiao.id
     *
     * @param id the value for shangpinbiao.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangpinbiao.feilei_id
     *
     * @return the value of shangpinbiao.feilei_id
     *
     * @mbg.generated
     */
    public String getFeileiId() {
        return feileiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangpinbiao.feilei_id
     *
     * @param feileiId the value for shangpinbiao.feilei_id
     *
     * @mbg.generated
     */
    public void setFeileiId(String feileiId) {
        this.feileiId = feileiId == null ? null : feileiId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangpinbiao.shangpin
     *
     * @return the value of shangpinbiao.shangpin
     *
     * @mbg.generated
     */
    public String getShangpin() {
        return shangpin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangpinbiao.shangpin
     *
     * @param shangpin the value for shangpinbiao.shangpin
     *
     * @mbg.generated
     */
    public void setShangpin(String shangpin) {
        this.shangpin = shangpin == null ? null : shangpin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangpinbiao.temp1
     *
     * @return the value of shangpinbiao.temp1
     *
     * @mbg.generated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangpinbiao.temp1
     *
     * @param temp1 the value for shangpinbiao.temp1
     *
     * @mbg.generated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangpinbiao.temp2
     *
     * @return the value of shangpinbiao.temp2
     *
     * @mbg.generated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangpinbiao.temp2
     *
     * @param temp2 the value for shangpinbiao.temp2
     *
     * @mbg.generated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangpinbiao.temp3
     *
     * @return the value of shangpinbiao.temp3
     *
     * @mbg.generated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangpinbiao.temp3
     *
     * @param temp3 the value for shangpinbiao.temp3
     *
     * @mbg.generated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangpinbiao.temp4
     *
     * @return the value of shangpinbiao.temp4
     *
     * @mbg.generated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangpinbiao.temp4
     *
     * @param temp4 the value for shangpinbiao.temp4
     *
     * @mbg.generated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shangpinbiao.temp5
     *
     * @return the value of shangpinbiao.temp5
     *
     * @mbg.generated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shangpinbiao.temp5
     *
     * @param temp5 the value for shangpinbiao.temp5
     *
     * @mbg.generated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
}