package com.lgs.entity;

public class YongHuBiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.yonghu
     *
     * @mbg.generated
     */
    private String yonghu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.mima
     *
     * @mbg.generated
     */
    private String mima;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.dengji
     *
     * @mbg.generated
     */
    private String dengji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.zhuangtai
     *
     * @mbg.generated
     */
    private String zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.cuowu
     *
     * @mbg.generated
     */
    private String cuowu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.temp1
     *
     * @mbg.generated
     */
    private String temp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.temp2
     *
     * @mbg.generated
     */
    private String temp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.temp3
     *
     * @mbg.generated
     */
    private String temp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.temp4
     *
     * @mbg.generated
     */
    private String temp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yonghubiao.temp5
     *
     * @mbg.generated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.id
     *
     * @return the value of yonghubiao.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.id
     *
     * @param id the value for yonghubiao.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.yonghu
     *
     * @return the value of yonghubiao.yonghu
     *
     * @mbg.generated
     */
    public String getYonghu() {
        return yonghu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.yonghu
     *
     * @param yonghu the value for yonghubiao.yonghu
     *
     * @mbg.generated
     */
    public void setYonghu(String yonghu) {
        this.yonghu = yonghu == null ? null : yonghu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.mima
     *
     * @return the value of yonghubiao.mima
     *
     * @mbg.generated
     */
    public String getMima() {
        return mima;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.mima
     *
     * @param mima the value for yonghubiao.mima
     *
     * @mbg.generated
     */
    public void setMima(String mima) {
        this.mima = mima == null ? null : mima.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.dengji
     *
     * @return the value of yonghubiao.dengji
     *
     * @mbg.generated
     */
    public String getDengji() {
        return dengji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.dengji
     *
     * @param dengji the value for yonghubiao.dengji
     *
     * @mbg.generated
     */
    public void setDengji(String dengji) {
        this.dengji = dengji == null ? null : dengji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.zhuangtai
     *
     * @return the value of yonghubiao.zhuangtai
     *
     * @mbg.generated
     */
    public String getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.zhuangtai
     *
     * @param zhuangtai the value for yonghubiao.zhuangtai
     *
     * @mbg.generated
     */
    public void setZhuangtai(String zhuangtai) {
        this.zhuangtai = zhuangtai == null ? null : zhuangtai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.cuowu
     *
     * @return the value of yonghubiao.cuowu
     *
     * @mbg.generated
     */
    public String getCuowu() {
        return cuowu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.cuowu
     *
     * @param cuowu the value for yonghubiao.cuowu
     *
     * @mbg.generated
     */
    public void setCuowu(String cuowu) {
        this.cuowu = cuowu == null ? null : cuowu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.temp1
     *
     * @return the value of yonghubiao.temp1
     *
     * @mbg.generated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.temp1
     *
     * @param temp1 the value for yonghubiao.temp1
     *
     * @mbg.generated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.temp2
     *
     * @return the value of yonghubiao.temp2
     *
     * @mbg.generated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.temp2
     *
     * @param temp2 the value for yonghubiao.temp2
     *
     * @mbg.generated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.temp3
     *
     * @return the value of yonghubiao.temp3
     *
     * @mbg.generated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.temp3
     *
     * @param temp3 the value for yonghubiao.temp3
     *
     * @mbg.generated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.temp4
     *
     * @return the value of yonghubiao.temp4
     *
     * @mbg.generated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.temp4
     *
     * @param temp4 the value for yonghubiao.temp4
     *
     * @mbg.generated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yonghubiao.temp5
     *
     * @return the value of yonghubiao.temp5
     *
     * @mbg.generated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yonghubiao.temp5
     *
     * @param temp5 the value for yonghubiao.temp5
     *
     * @mbg.generated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
}