package lgs.test;

public class CangKuBiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangkubiao.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangkubiao.cangku
     *
     * @mbg.generated
     */
    private String cangku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangkubiao.temp1
     *
     * @mbg.generated
     */
    private String temp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangkubiao.temp2
     *
     * @mbg.generated
     */
    private String temp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangkubiao.temp3
     *
     * @mbg.generated
     */
    private String temp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangkubiao.temp4
     *
     * @mbg.generated
     */
    private String temp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cangkubiao.temp5
     *
     * @mbg.generated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangkubiao.id
     *
     * @return the value of cangkubiao.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangkubiao.id
     *
     * @param id the value for cangkubiao.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangkubiao.cangku
     *
     * @return the value of cangkubiao.cangku
     *
     * @mbg.generated
     */
    public String getCangku() {
        return cangku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangkubiao.cangku
     *
     * @param cangku the value for cangkubiao.cangku
     *
     * @mbg.generated
     */
    public void setCangku(String cangku) {
        this.cangku = cangku == null ? null : cangku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangkubiao.temp1
     *
     * @return the value of cangkubiao.temp1
     *
     * @mbg.generated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangkubiao.temp1
     *
     * @param temp1 the value for cangkubiao.temp1
     *
     * @mbg.generated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangkubiao.temp2
     *
     * @return the value of cangkubiao.temp2
     *
     * @mbg.generated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangkubiao.temp2
     *
     * @param temp2 the value for cangkubiao.temp2
     *
     * @mbg.generated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangkubiao.temp3
     *
     * @return the value of cangkubiao.temp3
     *
     * @mbg.generated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangkubiao.temp3
     *
     * @param temp3 the value for cangkubiao.temp3
     *
     * @mbg.generated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangkubiao.temp4
     *
     * @return the value of cangkubiao.temp4
     *
     * @mbg.generated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangkubiao.temp4
     *
     * @param temp4 the value for cangkubiao.temp4
     *
     * @mbg.generated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cangkubiao.temp5
     *
     * @return the value of cangkubiao.temp5
     *
     * @mbg.generated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cangkubiao.temp5
     *
     * @param temp5 the value for cangkubiao.temp5
     *
     * @mbg.generated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
}