package lgs.test;

import com.lgs.entity.CangKuBiao;

public interface CangKuBiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangkubiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangkubiao
     *
     * @mbg.generated
     */
    int insert(CangKuBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangkubiao
     *
     * @mbg.generated
     */
    int insertSelective(CangKuBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangkubiao
     *
     * @mbg.generated
     */
    CangKuBiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangkubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CangKuBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cangkubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CangKuBiao record);
}