package lgs.test;

import com.lgs.entity.FenLeiBiao;

public interface FenLeiBiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenleibiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenleibiao
     *
     * @mbg.generated
     */
    int insert(FenLeiBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenleibiao
     *
     * @mbg.generated
     */
    int insertSelective(FenLeiBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenleibiao
     *
     * @mbg.generated
     */
    FenLeiBiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenleibiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FenLeiBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fenleibiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FenLeiBiao record);
}