package lgs.test;

public class GongYingShangBiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongyingshangbiao.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongyingshangbiao.gongyingshang
     *
     * @mbg.generated
     */
    private String gongyingshang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongyingshangbiao.temp1
     *
     * @mbg.generated
     */
    private String temp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongyingshangbiao.temp2
     *
     * @mbg.generated
     */
    private String temp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongyingshangbiao.temp3
     *
     * @mbg.generated
     */
    private String temp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongyingshangbiao.temp4
     *
     * @mbg.generated
     */
    private String temp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gongyingshangbiao.temp5
     *
     * @mbg.generated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongyingshangbiao.id
     *
     * @return the value of gongyingshangbiao.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongyingshangbiao.id
     *
     * @param id the value for gongyingshangbiao.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongyingshangbiao.gongyingshang
     *
     * @return the value of gongyingshangbiao.gongyingshang
     *
     * @mbg.generated
     */
    public String getGongyingshang() {
        return gongyingshang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongyingshangbiao.gongyingshang
     *
     * @param gongyingshang the value for gongyingshangbiao.gongyingshang
     *
     * @mbg.generated
     */
    public void setGongyingshang(String gongyingshang) {
        this.gongyingshang = gongyingshang == null ? null : gongyingshang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongyingshangbiao.temp1
     *
     * @return the value of gongyingshangbiao.temp1
     *
     * @mbg.generated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongyingshangbiao.temp1
     *
     * @param temp1 the value for gongyingshangbiao.temp1
     *
     * @mbg.generated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongyingshangbiao.temp2
     *
     * @return the value of gongyingshangbiao.temp2
     *
     * @mbg.generated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongyingshangbiao.temp2
     *
     * @param temp2 the value for gongyingshangbiao.temp2
     *
     * @mbg.generated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongyingshangbiao.temp3
     *
     * @return the value of gongyingshangbiao.temp3
     *
     * @mbg.generated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongyingshangbiao.temp3
     *
     * @param temp3 the value for gongyingshangbiao.temp3
     *
     * @mbg.generated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongyingshangbiao.temp4
     *
     * @return the value of gongyingshangbiao.temp4
     *
     * @mbg.generated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongyingshangbiao.temp4
     *
     * @param temp4 the value for gongyingshangbiao.temp4
     *
     * @mbg.generated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gongyingshangbiao.temp5
     *
     * @return the value of gongyingshangbiao.temp5
     *
     * @mbg.generated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gongyingshangbiao.temp5
     *
     * @param temp5 the value for gongyingshangbiao.temp5
     *
     * @mbg.generated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
}