package lgs.test;

import com.lgs.entity.KeHuBiao;

public interface KeHuBiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kehubiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kehubiao
     *
     * @mbg.generated
     */
    int insert(KeHuBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kehubiao
     *
     * @mbg.generated
     */
    int insertSelective(KeHuBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kehubiao
     *
     * @mbg.generated
     */
    KeHuBiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kehubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(KeHuBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kehubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(KeHuBiao record);
}