package lgs.test;

import com.lgs.entity.RuKuShengQingBiao;

public interface RuKuShengQingBiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rukushenqingbiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rukushenqingbiao
     *
     * @mbg.generated
     */
    int insert(RuKuShengQingBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rukushenqingbiao
     *
     * @mbg.generated
     */
    int insertSelective(RuKuShengQingBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rukushenqingbiao
     *
     * @mbg.generated
     */
    RuKuShengQingBiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rukushenqingbiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RuKuShengQingBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rukushenqingbiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RuKuShengQingBiao record);
}