package lgs.test;

public class RuKuShengQingBiao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.shangpin_id
     *
     * @mbg.generated
     */
    private String shangpinId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.shuliang
     *
     * @mbg.generated
     */
    private String shuliang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.cangku_id
     *
     * @mbg.generated
     */
    private String cangkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.shenqingshijian
     *
     * @mbg.generated
     */
    private String shenqingshijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.shenheshijian
     *
     * @mbg.generated
     */
    private String shenheshijian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.yonghu_id
     *
     * @mbg.generated
     */
    private String yonghuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.baozhiqikaishi
     *
     * @mbg.generated
     */
    private String baozhiqikaishi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.baozhiqijieshu
     *
     * @mbg.generated
     */
    private String baozhiqijieshu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.bianhao
     *
     * @mbg.generated
     */
    private String bianhao;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.zhuangtai
     *
     * @mbg.generated
     */
    private String zhuangtai;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.shuoming
     *
     * @mbg.generated
     */
    private String shuoming;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.temp1
     *
     * @mbg.generated
     */
    private String temp1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.temp2
     *
     * @mbg.generated
     */
    private String temp2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.temp3
     *
     * @mbg.generated
     */
    private String temp3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.temp4
     *
     * @mbg.generated
     */
    private String temp4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rukushenqingbiao.temp5
     *
     * @mbg.generated
     */
    private String temp5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.id
     *
     * @return the value of rukushenqingbiao.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.id
     *
     * @param id the value for rukushenqingbiao.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.shangpin_id
     *
     * @return the value of rukushenqingbiao.shangpin_id
     *
     * @mbg.generated
     */
    public String getShangpinId() {
        return shangpinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.shangpin_id
     *
     * @param shangpinId the value for rukushenqingbiao.shangpin_id
     *
     * @mbg.generated
     */
    public void setShangpinId(String shangpinId) {
        this.shangpinId = shangpinId == null ? null : shangpinId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.shuliang
     *
     * @return the value of rukushenqingbiao.shuliang
     *
     * @mbg.generated
     */
    public String getShuliang() {
        return shuliang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.shuliang
     *
     * @param shuliang the value for rukushenqingbiao.shuliang
     *
     * @mbg.generated
     */
    public void setShuliang(String shuliang) {
        this.shuliang = shuliang == null ? null : shuliang.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.cangku_id
     *
     * @return the value of rukushenqingbiao.cangku_id
     *
     * @mbg.generated
     */
    public String getCangkuId() {
        return cangkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.cangku_id
     *
     * @param cangkuId the value for rukushenqingbiao.cangku_id
     *
     * @mbg.generated
     */
    public void setCangkuId(String cangkuId) {
        this.cangkuId = cangkuId == null ? null : cangkuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.shenqingshijian
     *
     * @return the value of rukushenqingbiao.shenqingshijian
     *
     * @mbg.generated
     */
    public String getShenqingshijian() {
        return shenqingshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.shenqingshijian
     *
     * @param shenqingshijian the value for rukushenqingbiao.shenqingshijian
     *
     * @mbg.generated
     */
    public void setShenqingshijian(String shenqingshijian) {
        this.shenqingshijian = shenqingshijian == null ? null : shenqingshijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.shenheshijian
     *
     * @return the value of rukushenqingbiao.shenheshijian
     *
     * @mbg.generated
     */
    public String getShenheshijian() {
        return shenheshijian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.shenheshijian
     *
     * @param shenheshijian the value for rukushenqingbiao.shenheshijian
     *
     * @mbg.generated
     */
    public void setShenheshijian(String shenheshijian) {
        this.shenheshijian = shenheshijian == null ? null : shenheshijian.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.yonghu_id
     *
     * @return the value of rukushenqingbiao.yonghu_id
     *
     * @mbg.generated
     */
    public String getYonghuId() {
        return yonghuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.yonghu_id
     *
     * @param yonghuId the value for rukushenqingbiao.yonghu_id
     *
     * @mbg.generated
     */
    public void setYonghuId(String yonghuId) {
        this.yonghuId = yonghuId == null ? null : yonghuId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.baozhiqikaishi
     *
     * @return the value of rukushenqingbiao.baozhiqikaishi
     *
     * @mbg.generated
     */
    public String getBaozhiqikaishi() {
        return baozhiqikaishi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.baozhiqikaishi
     *
     * @param baozhiqikaishi the value for rukushenqingbiao.baozhiqikaishi
     *
     * @mbg.generated
     */
    public void setBaozhiqikaishi(String baozhiqikaishi) {
        this.baozhiqikaishi = baozhiqikaishi == null ? null : baozhiqikaishi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.baozhiqijieshu
     *
     * @return the value of rukushenqingbiao.baozhiqijieshu
     *
     * @mbg.generated
     */
    public String getBaozhiqijieshu() {
        return baozhiqijieshu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.baozhiqijieshu
     *
     * @param baozhiqijieshu the value for rukushenqingbiao.baozhiqijieshu
     *
     * @mbg.generated
     */
    public void setBaozhiqijieshu(String baozhiqijieshu) {
        this.baozhiqijieshu = baozhiqijieshu == null ? null : baozhiqijieshu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.bianhao
     *
     * @return the value of rukushenqingbiao.bianhao
     *
     * @mbg.generated
     */
    public String getBianhao() {
        return bianhao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.bianhao
     *
     * @param bianhao the value for rukushenqingbiao.bianhao
     *
     * @mbg.generated
     */
    public void setBianhao(String bianhao) {
        this.bianhao = bianhao == null ? null : bianhao.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.zhuangtai
     *
     * @return the value of rukushenqingbiao.zhuangtai
     *
     * @mbg.generated
     */
    public String getZhuangtai() {
        return zhuangtai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.zhuangtai
     *
     * @param zhuangtai the value for rukushenqingbiao.zhuangtai
     *
     * @mbg.generated
     */
    public void setZhuangtai(String zhuangtai) {
        this.zhuangtai = zhuangtai == null ? null : zhuangtai.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.shuoming
     *
     * @return the value of rukushenqingbiao.shuoming
     *
     * @mbg.generated
     */
    public String getShuoming() {
        return shuoming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.shuoming
     *
     * @param shuoming the value for rukushenqingbiao.shuoming
     *
     * @mbg.generated
     */
    public void setShuoming(String shuoming) {
        this.shuoming = shuoming == null ? null : shuoming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.temp1
     *
     * @return the value of rukushenqingbiao.temp1
     *
     * @mbg.generated
     */
    public String getTemp1() {
        return temp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.temp1
     *
     * @param temp1 the value for rukushenqingbiao.temp1
     *
     * @mbg.generated
     */
    public void setTemp1(String temp1) {
        this.temp1 = temp1 == null ? null : temp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.temp2
     *
     * @return the value of rukushenqingbiao.temp2
     *
     * @mbg.generated
     */
    public String getTemp2() {
        return temp2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.temp2
     *
     * @param temp2 the value for rukushenqingbiao.temp2
     *
     * @mbg.generated
     */
    public void setTemp2(String temp2) {
        this.temp2 = temp2 == null ? null : temp2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.temp3
     *
     * @return the value of rukushenqingbiao.temp3
     *
     * @mbg.generated
     */
    public String getTemp3() {
        return temp3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.temp3
     *
     * @param temp3 the value for rukushenqingbiao.temp3
     *
     * @mbg.generated
     */
    public void setTemp3(String temp3) {
        this.temp3 = temp3 == null ? null : temp3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.temp4
     *
     * @return the value of rukushenqingbiao.temp4
     *
     * @mbg.generated
     */
    public String getTemp4() {
        return temp4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.temp4
     *
     * @param temp4 the value for rukushenqingbiao.temp4
     *
     * @mbg.generated
     */
    public void setTemp4(String temp4) {
        this.temp4 = temp4 == null ? null : temp4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rukushenqingbiao.temp5
     *
     * @return the value of rukushenqingbiao.temp5
     *
     * @mbg.generated
     */
    public String getTemp5() {
        return temp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rukushenqingbiao.temp5
     *
     * @param temp5 the value for rukushenqingbiao.temp5
     *
     * @mbg.generated
     */
    public void setTemp5(String temp5) {
        this.temp5 = temp5 == null ? null : temp5.trim();
    }
}