package lgs.test;

import com.lgs.entity.ShangPingBiao;

public interface ShangPingBiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangpinbiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangpinbiao
     *
     * @mbg.generated
     */
    int insert(ShangPingBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangpinbiao
     *
     * @mbg.generated
     */
    int insertSelective(ShangPingBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangpinbiao
     *
     * @mbg.generated
     */
    ShangPingBiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangpinbiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShangPingBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shangpinbiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShangPingBiao record);
}