package lgs.test;

import com.lgs.entity.YongHuBiao;

public interface YongHuBiaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghubiao
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghubiao
     *
     * @mbg.generated
     */
    int insert(YongHuBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghubiao
     *
     * @mbg.generated
     */
    int insertSelective(YongHuBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghubiao
     *
     * @mbg.generated
     */
    YongHuBiao selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(YongHuBiao record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yonghubiao
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(YongHuBiao record);
}